### PR TITLE
Moved object id check logic from a controller to a middleware

### PR DESCRIPTION
**Pull request by Daniel-Sogbey**
Moved checkObject ID validation logic from controller to middleware

### CODE REVIEW

**Comment by lgyamfi** [comment]
thanks man @Daniel-Sogbey there are some merge conflicts. could you kindly resolve them? thanks!

**Comment by Daniel-Sogbey** [comment]
@starboyles Fixed

**Comment by Daniel-Sogbey** [comment]
@starboyles can you drop for me here the Discord server url

**Comment by lgyamfi** [comment]
> @starboyles Fixed

Appreciate!

**Comment by lgyamfi** [comment]
> @starboyles can you drop for me here the Discord server url

Sure here you go! https://discord.gg/ZSVSdKgZ

**Pull request merged**
